version: "3.4"

services:

  web:
    build: ../web    
    depends_on:
      - api
    ports:
      - 9001:80

  api:
    build: .
    depends_on:
      - mongo
    restart: always
    ports:
      - 9000:80

  mongo:
    image: mongo