version: "3.4"

services:

  web:
    build: ../web    
    depends_on:
      - api
    ports:
      - 9001:80

  api:
    build: .
    depends_on:
      - sqlserver
    restart: always
    ports:
      - 9000:3000

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"