version: "3.4"

services:

  web:
    build: ../web    
    depends_on:
      - api
    ports:
      - 9001:80

  api:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - 9000:9000

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password